-- Ishan Khetarpal
-- Created: 13 April 2016
-- Updated: 13 April 2016

-- CREATE DATABASE TABLES:

 CREATE TABLE PRIORITIES (
    PRIORITY_CODE      VARCHAR2(15),
    DESCRIPTION        VARCHAR2(255)
        CONSTRAINT PRIORITIES_DESCRIPTION_NN         NOT NULL,
    CONSTRAINT PRIORITIES_PRIORITY_CODE_PK       PRIMARY KEY (PRIORITY_CODE));
    
-- TODO add more    

-- INSERT BASIC DATA INTO TABLES:

INSERT ALL
    INTO PRIORITIES(PRIORITY_CODE,
                    DESCRIPTION)
    VALUES ('ALPHA',
            'NON LIFE THREATENING, TIME WILL NOT AFFECT OUTCOME')
    INTO PRIORITIES(PRIORITY_CODE,
                    DESCRIPTION)
    VALUES ('BRAVO',
            'NON LIFE THREATENING, TIME MAY AFFECT OUTCOME')
    INTO PRIORITIES(PRIORITY_CODE,
                    DESCRIPTION)
    VALUES ('CHARLIE',
            'POSSIBLY LIFE THREATENING, TIME MAY AFFECT OUTCOME')
    INTO PRIORITIES(PRIORITY_CODE,
                    DESCRIPTION)
    VALUES ('DELTA',
            'LIFE THREATENING, HIGHEST PRIORITY')
SELECT *
FROM DUAL;

-- TODO add more 
    